---
title: "Oxygen concentration projections"
author: "J. L. Couture"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googledrive)
library(ncdf4)
library(mregions)
library(sf)
library(ggmap)
library(viridis)
library(weathermetrics)
library(chron)
library(RColorBrewer)
library(lattice)
library(gganimate)
library(patchwork)
library(lubridate)


```

## CMIP6 Dissolved Oxygen Concentration Data

Data were pulled from the [Earth System Grid Federation]("https://esgf.llnl.gov/") site which houses the CMIP6 database. I have added the SST netCDF file to the google drive `(myDrive > CI > data > climateData > cmip6 > tos_Omon_ACCESS-CM2_ssp126_r1i1p1f1_gn_210101-230012.nc)`

```{r getDat}

datFile<-"data/cmip6/o2yr.nc"

drive_download("o2_Oyr_ACCESS-ESM1-5_ssp126_r1i1p1f1_gn_2015-2100.nc",
                   path=datFile,
                   overwrite = TRUE)

o2<-nc_open(datFile)

```

```{r pullVars, echo=FALSE}

lon<-ncvar_get(o2,"longitude")
lat<-ncvar_get(o2,"latitude")
o2Var<-ncvar_get(o2,"o2") # in mole concentration of dissolved oxygen in sea water
timeBnd<-ncvar_get(o2,"time_bnds")
depth<-ncvar_get(o2,"lev")

ttl<-ncatt_get(o2,"o2","long_name")
ttlNm<-as.character(ttl$value)

```


```{r}

# EmpowerDat plotting function

mapO2CDF<-function(lat,lon,var,title){
  
  titletext <- title
  expand.grid(lat=lat[1,],lon=lon[,1])%>%
    mutate(lon=ifelse(lon>180,-(360-lon),lon),
           ph=as.vector(t(var)))%>%
    ggplot()+
    geom_point(aes(x=lon,y=lat,color=ph),size=1)+
    borders("world",colour="black",fill="grey")+
    scale_color_viridis(na.value="white",name="[Oxygen]\n(mol m-3)")+
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle(titletext)+
    theme_bw()
  
}

mapO2CDF(lat,lon,var=o2Var[,,3,1],ttlNm)

```
#### Convert arrays to DF

```{r}

## convert the array to df ---> shallow depth: 25m
o2Dfshallow<-NULL

datesDf<-tibble(date=as_date(timeBnd[1,],origin="1850-01-01"))%>%
  mutate(year=year(date))

for (i in 1:nrow(datesDf)){ # iterate over years
    
    tempDf <- expand.grid(lat=lat[1,],lon=lon[,1])%>%
      mutate(lon=ifelse(lon>180,-(360-lon),lon),
             o2=as.vector(t(o2Var[,,3,i])))%>% # 3 is depth of 25m
      mutate(year=as.numeric(datesDf[i,"year"]))
  
    o2Dfshallow = o2Dfshallow %>% bind_rows(tempDf)
}

## Deeper: >425m

o2DfDeep<-NULL

for (i in 1:nrow(datesDf)){ # iterate over years
    
    tempDf <- expand.grid(lat=lat[1,],lon=lon[,1])%>%
      mutate(lon=ifelse(lon>180,-(360-lon),lon),
             o2=as.vector(t(o2Var[,,26,i])))%>% # 26 is depth of 427.3156m
      mutate(year=as.numeric(datesDf[i,"year"]))
  
    o2DfDeep = o2DfDeep %>% bind_rows(tempDf)
}


```

#### Construct GIF

```{r}
### gganimate

### Shallow

o2sAnim<-ggplot(o2Dfshallow,aes(x=lon,y=lat,color=o2),size=1)+
  geom_point()+
  borders("world",colour="black",fill="grey")+
  scale_color_viridis(na.value="white",name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  theme(legend.direction = "vertical",legend.position = "right")+
  coord_quickmap()+
  theme_bw()+
  labs(title="Annual Dissolved Oxygen Concentration: shallow (25m)",subtitle = "Year: {closest_state}")+
  transition_states(year,transition_length = 2)
  
animate(o2sAnim)

# anim_save(filename = "meanO2conc25m2100.gif")

### Deep

o2dAnim<-ggplot(o2DfDeep,aes(x=lon,y=lat,color=o2),size=1)+
  geom_point()+
  borders("world",colour="black",fill="grey")+
  scale_color_viridis(na.value="white",name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  theme(legend.direction = "vertical",legend.position = "right")+
  coord_quickmap()+
  theme_bw()+
  labs(title="Annual Dissolved Oxygen Concentration: deep (>425m)",subtitle = "Year: {closest_state}")+
  transition_states(year,transition_length = 2)
  
animate(o2dAnim)

# anim_save(filename = "meanO2conc427m2100.gif")

```


### Difference in Temp 2020 - 2060, 2020 - 2100

```{r}

o2DiffsSh<-o2Dfshallow%>%
  filter(year==2020)%>%
  rename(o22020=o2)%>%
  bind_cols(o2Dfshallow%>%
              filter(year==2060)%>%
              select(o22060=o2),
            o2Dfshallow%>%
              filter(year==2100)%>%
              select(o22100=o2))%>%
    mutate(diff2060=o22060-o22020,
           diff2100=o22100-o22020)

o2DiffsDp<-o2DfDeep%>%
  filter(year==2020)%>%
  rename(o22020=o2)%>%
  bind_cols(o2DfDeep%>%
              filter(year==2060)%>%
              select(o22060=o2),
            o2DfDeep%>%
              filter(year==2100)%>%
              select(o22100=o2))%>%
    mutate(diff2060=o22060-o22020,
           diff2100=o22100-o22020)

mapDiffs2060<-o2DiffsSh%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2060),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-0.1,0.1),name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("Projected Change in Oxygen Concentration: shallow (25m)",subtitle = "2020 to 2060")+
    theme_bw()

mapDiffs2100<-o2DiffsSh%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2100),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-0.1,0.1),name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("",subtitle = "2020 to 2100")+
    theme_bw()

#### at depth

mapDiffs2060dp<-o2DiffsDp%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2060),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-0.1,0.1),name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("Projected Change in Oxygen Concentration: deep (>425m)",subtitle = "2020 to 2060")+
    theme_bw()

mapDiffs2100dp<-o2DiffsDp%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2100),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-0.1,0.1),name="[Oxygen]\n(mol m-3)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("",subtitle = "2020 to 2100")+
    theme_bw()

```


```{r}

mapDiffs2060+mapDiffs2100+
  plot_layout(guides = "collect")

```


```{r}

mapDiffs2060dp+mapDiffs2100dp+
  plot_layout(guides = "collect")

```


###### Delete data file from local

```{r}

if (file.exists(datFile)) {
 unlink(datFile)
 cat(paste("The file has been deleted: ",datFile))
}

```

#### Revillagigedo MPA

```{r RevillagigedoMPA}

revShp<-st_read("RevillagigedoMPA/WDPA_WDOECM_Mar2022_Public_555629385_shp/WDPA_WDOECM_Mar2022_Public_555629385_shp_0/WDPA_WDOECM_Mar2022_Public_555629385_shp-polygons.shp")

revBB<-st_bbox(revShp)
buff <- 7

ploArea<-st_bbox(c(xmin=as.numeric(revBB$xmin-buff),
                   xmax=as.numeric(revBB$xmax+buff),
                   ymin=as.numeric(revBB$ymin-buff),
                   ymax=as.numeric(revBB$ymax+buff)),crs = st_crs(revShp))

### isolate base layers

mxShp<-map_data("world",region="Mexico")%>%
  st_as_sf(.,
           coords=c("long","lat"),
           crs="+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")%>%
  group_by(group) %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("POLYGON")%>%
  st_crop(.,ploArea)


# mrRev<-mr_shp(key="MarineRegions:eez",
#              filter="Mexican Exclusive Economic Zone")%>%
#   filter(long > as.numeric(ploArea$xmin),
#          long < as.numeric(ploArea$xmax))%>%
#   filter(lat > as.numeric(ploArea$ymin),
#          lat < as.numeric(ploArea$ymax)) ### doesn't show up on map, all ploArea is within the eez and doesn't cross the boundary

```

```{r}

### isloate rev data from o2 (shallow) data

o2Rev<-o2DiffsSh%>%
  filter(lon>as.numeric(ploArea$xmin),
         lon<as.numeric(ploArea$xmax),
         lat>as.numeric(ploArea$ymin),
         lat<as.numeric(ploArea$ymax))%>%
  # st_as_sf(coords=c("lon","lat"),
  #          crs=4326)
  mutate(ave2020=mean(o22020,na.rm=T),
         o2perc60=(diff2060/ave2020)*100)
  
```

```{r}

o2DiffShRev<-ggplot()+
  geom_tile(data=o2Rev,aes(x=lon,y=lat,fill=o2perc60),width=1,height=1)+
    # geom_sf(mxShp,colour="black",fill="grey")+
    geom_sf(data=revShp,color="white",fill=NA)+
  geom_sf(data=mxShp)+
  # geom_sf(data=mrRev)+
  # scale_fill_viridis_c(limits=c(0,0.25),direction=-1,name="[Oxygen]\n(mol m-3)")+
  scale_fill_gradient2(low = "#0a6165",high = "#da4325",mid = "#e7e1bc",midpoint = 0,name="% change in\n[oxygen]")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0),limits = c(ploArea$ymin,ploArea$ymax+0.1))+
    theme(legend.direction = "vertical",legend.position = "right")+
    ggtitle("Projected Change in Oxygen Concentration: shallow (25m)",subtitle = "2020 to 2060")+
    theme_bw()
  
o2DiffShRev

```

```{r}

o2DiffDpRev<-o2DiffsDp%>%
  filter(lon>as.numeric(ploArea$xmin),
         lon<as.numeric(ploArea$xmax),
         lat>as.numeric(ploArea$ymin),
         lat<as.numeric(ploArea$ymax))%>%
   mutate(ave2020=mean(o22020,na.rm=T),
         o2perc60=(diff2060/ave2020)*100)%>%
  ggplot()+
  geom_tile(data=o2Rev,aes(x=lon,y=lat,fill=o2perc60),width=1,height=1)+
    # geom_sf(mxShp,colour="black",fill="grey")+
    geom_sf(data=revShp,color="white",fill=NA)+
  geom_sf(data=mxShp)+
  # scale_fill_viridis_c(limits=c(0,0.25),direction=-1,name="[Oxygen]\n(mol m-3)")+
  scale_fill_gradient2(low = "#0a6165",high = "#da4325",mid = "#e7e1bc",midpoint = 0,name="% change in\n[oxygen]")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0),limits = c(ploArea$ymin,ploArea$ymax+0.1))+
    theme(legend.direction = "vertical",legend.position = "right")+
    ggtitle("Projected Change in Oxygen Concentration: deep (>425m)",subtitle = "2020 to 2060")+
    theme_bw()
  
o2DiffDpRev

```