---
title: "Salinity projections"
author: "J. L. Couture"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googledrive)
library(ncdf4)
library(mregions)
library(sf)
library(ggmap)
library(viridis)
library(weathermetrics)
library(chron)
library(RColorBrewer)
library(lattice)
library(gganimate)


```

## CMIP6 SST Data

Data were pulled from the [Earth System Grid Federation]("https://esgf.llnl.gov/") site which houses the CMIP6 database. I have added the SST netCDF file to the google drive `(myDrive > CI > data > climateData > cmip6 > tos_Omon_ACCESS-CM2_ssp126_r1i1p1f1_gn_210101-230012.nc)`

```{r getDat}

datFile<-"data/cmip6/sssMon.nc"

drive_download("sos_Omon_ACCESS-CM2_ssp126_r1i1p1f1_gn_201501-210012.nc",
                   path=datFile,
                   overwrite = TRUE)

sss<-nc_open(datFile)

```

```{r pullVars, echo=FALSE}

lon<-ncvar_get(sss,"longitude")
lat<-ncvar_get(sss,"latitude")
sssVar<-ncvar_get(sss,"sos") # in degC
timeBnd<-ncvar_get(sss,"time_bnds")
# year<-ncvar_get(sst,"Year")

ttl<-ncatt_get(sss,"sos","long_name")
ttlNm<-as.character(ttl$value)

```


```{r}

# EmpowerDat plotting function

mapSalCDF<-function(lat,lon,var,title){
  
  titletext <- title
  expand.grid(lat=lat[1,],lon=lon[,1])%>%
    mutate(lon=ifelse(lon>180,-(360-lon),lon),
           ph=as.vector(t(var)))%>%
    ggplot()+
    geom_point(aes(x=lon,y=lat,color=ph),size=1)+
    borders("world",colour="black",fill="grey")+
    scale_color_viridis(na.value="white",name="Surface Salinity\n(ppt)")+
    scale_x_continuous(expand = c(0,0))+
    scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle(titletext)+
    theme_bw()
  
}

mapSalCDF(lat,lon,var=sssVar[,,1],ttlNm)

```
#### Calculate mean SST across months for each year

```{r}

## convert the array to df

## calculate mean temperatures for a year and paste into a new DF: aveSSSdf

newYr<-seq(1,ncol(timeBnd),by=12)
aveSSSdf<-NULL
datesDf<-tibble(date=as_date(timeBnd[1,],origin="1850-01-01"))%>%
  mutate(year=year(date))


for(i in 1:length(newYr)){
  
  yrDf<-expand.grid(lat=lat[1,],lon=lon[,1])%>%
    mutate(lon=ifelse(lon>180,-(360-lon),lon))
  
  
  for(j in 1:12){ # iterate over time
    k=newYr[i]+j-1
    
  monDf <- expand.grid(lat=lat[1,],lon=lon[,1])%>%
    mutate(lon=ifelse(lon>180,-(360-lon),lon),
           sss=as.vector(t(sssVar[,,k])))
  
  yrDf = yrDf %>% bind_cols(monDf%>%select(sss))    
  
  }
  yrDf<-yrDf%>%
    mutate(aveSSS=rowMeans(.[-1:-2],na.rm = TRUE))%>%
    select(lat,lon,aveSSS)%>%
    mutate(year=2014+i)#datesDf[k,"year"])
  
  aveSSSdf<-aveSSSdf%>%
    bind_rows(.,yrDf)
  
  i=i+1
}
  
  
# testdf<-aveSSSdf%>%
#   filter(year %in% 2015:2017)
```

#### Construct GIF

```{r}
### gganimate


sssAnim<-ggplot(aveSSSdf,aes(x=lon,y=lat,color=aveSSS),size=1)+
  geom_point()+
  borders("world",colour="black",fill="grey")+
  scale_color_viridis(na.value="white",name="Salinity (ppt)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  theme(legend.direction = "vertical",legend.position = "right")+
  coord_quickmap()+
  theme_bw()+
  labs(title="Average Annual Sea Surface Salinity",subtitle = "Year: {closest_state}")+
  transition_states(year,transition_length = 2)
  
animate(sssAnim)

# anim_save(filename = "meanAnnSss2100.gif")

```


### Difference in Temp 2020 - 2060, 2020 - 2100

```{r}

sssDiffs<-aveSSSdf%>%
  filter(year==2020)%>%
  rename(sss2020=aveSSS)%>%
  bind_cols(aveSSSdf%>%
              filter(year==2060)%>%
              select(sss2060=aveSSS),
            aveSSSdf%>%
              filter(year==2100)%>%
              select(sss2100=aveSSS))%>%
    mutate(diff2060=sss2060-sss2020,
           diff2100=sss2100-sss2020)

mapDiffs2060<-sssDiffs%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2060),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-5,3),name="Salinity (ppt)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("Projected Change in SSS",subtitle = "2020 to 2060")+
    theme_bw()

mapDiffs2100<-sssDiffs%>%
  ggplot()+
  geom_point(aes(x=lon,y=lat,color=diff2100),size=1)+
    borders("world",colour="black",fill="grey")+
    # scale_color_viridis(na.value="white",name="Temperature (C)")+
  scale_color_gradient2(low="blue4",mid = "white",high = "brown3",midpoint = 0,limits=c(-5,3),name="Salinity (ppt)")+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
    theme(legend.direction = "vertical",legend.position = "right")+
    coord_quickmap()+
    ggtitle("Projected Change in SSS",subtitle = "2020 to 2100")+
    theme_bw()

```


```{r}

mapDiffs2060

```


```{r}

mapDiffs2100

```


###### Delete data file from local

```{r}

if (file.exists(datFile)) {
 unlink(datFile)
 cat(paste("The file has been deleted: ",datFile))
}

```

#### Revillagigedo MPA

```{r RevillagigedoMPA}

revShp<-st_read("RevillagigedoMPA/WDPA_WDOECM_Mar2022_Public_555629385_shp/WDPA_WDOECM_Mar2022_Public_555629385_shp_0/WDPA_WDOECM_Mar2022_Public_555629385_shp-polygons.shp")

revBB<-st_bbox(revShp)
buff <- 7

ploArea<-st_bbox(c(xmin=as.numeric(revBB$xmin-buff),
                   xmax=as.numeric(revBB$xmax+buff),
                   ymin=as.numeric(revBB$ymin-buff),
                   ymax=as.numeric(revBB$ymax+buff)),crs = st_crs(revShp))

### isolate base layers

mxShp<-map_data("world",region="Mexico")%>%
  st_as_sf(.,
           coords=c("long","lat"),
           crs="+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")%>%
  group_by(group) %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("POLYGON")%>%
  st_crop(.,ploArea)


mrRev<-mr_shp(key="MarineRegions:eez",
             filter="Mexican Exclusive Economic Zone")%>%
  filter(long > as.numeric(ploArea$xmin),
         long < as.numeric(ploArea$xmax))%>%
  filter(lat > as.numeric(ploArea$ymin),
         lat < as.numeric(ploArea$ymax)) ### doesn't show up on map, all ploArea is within the eez and doesn't cross the boundary

```

```{r}

### isloate rev data from o2 (shallow) data

sssRev<-sssDiffs%>%
  filter(lon>as.numeric(ploArea$xmin),
         lon<as.numeric(ploArea$xmax),
         lat>as.numeric(ploArea$ymin),
         lat<as.numeric(ploArea$ymax))#%>%
  # st_as_sf(coords=c("lon","lat"),
  #          crs=4326)

```

```{r}

sssRevPlt<-ggplot()+
  geom_tile(data=sssRev,aes(x=lon,y=lat,fill=diff2060),width=1,height=1)+
    # geom_sf(mxShp,colour="black",fill="grey")+
    geom_sf(data=revShp,color="grey21",fill=NA)+
  geom_sf(data=mxShp)+
  # geom_sf(data=mrRev)+
  # scale_fill_viridis_c(limits=c(0,2.1),name="degC")+
  scale_fill_gradient2(low = "#0a6165",high = "#da4325",mid = "#e7e1bc",midpoint = 0,name="ppt")+
  # scale_fill_brewer(type="div",palette = "BrGr")+ ## brewer are not continuous, only discrete
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0),limits = c(ploArea$ymin,ploArea$ymax+0.1))+
    theme(legend.direction = "vertical",legend.position = "right")+
    ggtitle("Projected Change in Sea Surface Salinity",subtitle = "2020 to 2060")+
    theme_bw()
  
sssRevPlt

```
